/*
 * This file was automatically generated by EvoSuite
 */

package org.jbehave.core.failures;

import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import org.jbehave.core.failures.BeforeOrAfterFailed;


public class BeforeOrAfterFailedEvoSuiteTest {


  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 org.jbehave.core.failures.BeforeOrAfterFailed.<init>(Ljava/lang/Throwable;)V: root-Branch
   */
  @Test
  public void test0()  throws Throwable  {
      BeforeOrAfterFailed beforeOrAfterFailed0 = new BeforeOrAfterFailed((Throwable) null);
      BeforeOrAfterFailed beforeOrAfterFailed1 = null;
      try {
        beforeOrAfterFailed1 = new BeforeOrAfterFailed((Method) null, (Throwable) beforeOrAfterFailed0);
      }catch(NullPointerException e) {
        /*
         * no message in exception (getMessage() returned null)
         */
        /*
      %%%<ex><className val="NullPointerException"/><stackDepth val="14"/><causeDepth val="0"/><source val="org.jbehave.core.failures.BeforeOrAfterFailed.&lt;init&gt;(BeforeOrAfterFailed.java:11)"/></ex>%%%
         */
      }
  }
}
